name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Build Docker image
        run: docker build -t yuriydovzhyk/frontend_kapusta_dev:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: yuriydovzhyk/frontend_kapusta_dev:latest
      - name: Deploy container to GitHub
        uses: docker/deploy-action@v1.2.0
        with:
          name: capusta-frontend
          image: yuriydovzhyk/frontend_kapusta_dev:latest
          registry: ghcr.io
          token: ${{ secrets.TOKEN }}
      
      
      
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
#       - name: Build and push image
#         uses: docker/build-push-action@v3
#         with:
#           push: true
#           tags: yuriydovzhyk/frontend_kapusta_dev:latest
#       - name: Setup Node.js
#         uses: actions/setup-node@v3.6.0
#         with:
#           node-version: '16.x'
#       - name: Install dependencies
#         run: npm install
        
#       - name: Start the server
#         run: node app.js
